<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LocationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locations')->insert([
            [
                'id' => 1,
                'name' => 'Menara MAIWP',
                'address' => 'Menara MAIWP, 39, Lrg Haji Hussein 2, Chow Kit, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1546,
                'longitude' => 101.6969,
                'radius_meters' => 100,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Menara MAIWP',
                'address' => 'Menara MAIWP, 39, Lrg Haji Hussein 2, Chow Kit, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1546,
                'longitude' => 101.6969,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Taman Shamelin Perkasa',
                'address' => 'No. 60, Jalan 4/91, Taman Shamelin Perkasa, 56100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1347,
                'longitude' => 101.7434,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Masjid Negara',
                'address' => 'Jalan Perdana, Tasik Perdana, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1416,
                'longitude' => 101.6901,
                'radius_meters' => 75,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) KLSC Wangsa Maju',
                'address' => 'KLSC @ Wangsa Maju, Lot G27, Ground Floor, AEON BiG Wangsa Maju, Seksyen 10, Wangsa Maju, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1943,
                'longitude' => 101.7479,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Presint 9 Putrajaya',
                'address' => 'Aras Bawah, Blok B, Kompleks Komersial Fasa 2, Presint 9, 62250 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9258,
                'longitude' => 101.6864,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Presint Diplomatik Putrajaya',
                'address' => 'No. 10, Jalan Diplomatik 1/1, Presint 15, 62050 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9327,
                'longitude' => 101.6756,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Masjid At-Taqwa, Taman Tun Dr. Ismail',
                'address' => 'Jalan Datuk Sulaiman, Taman Tun Dr Ismail, 60000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1478,
                'longitude' => 101.6353,
                'radius_meters' => 75,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) UTC Pudu Sentral',
                'address' => 'Unit 2-13A, Tingkat 2, UTC Pudu Sentral, Jalan Pudu, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1438,
                'longitude' => 101.7013,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Masjid Imam Al-Ghazali, Kepong',
                'address' => 'Jalan Rimbunan Raya 1, Laman Rimbunan, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2053,
                'longitude' => 101.6417,
                'radius_meters' => 75,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'name' => 'Pusat Pungutan Zakat (PPZ-MAIWP) Times Square, Labuan',
                'address' => 'Lot No. U028, Tingkat Bawah, Times Square, Jalan Merdeka, 87000 Labuan, Wilayah Persekutuan Labuan, Malaysia',
                'latitude' => 5.2804,
                'longitude' => 115.2438,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'name' => 'Kompleks Darul Hidayah MAIWP',
                'address' => 'Kompleks Darul Hidayah MAIWP, Jalan Sentul Perdana, Sentul Perdana, 51000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1728,
                'longitude' => 101.6834,
                'radius_meters' => 100,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'name' => 'Sekolah Menengah Agama MAIWP Kuala Lumpur',
                'address' => 'Jalan Batu Muda, Kampung Batu Muda, 68100 Batu Caves, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2097,
                'longitude' => 101.6774,
                'radius_meters' => 150,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'name' => 'Sekolah Menengah Agama MAIWP Labuan',
                'address' => 'Peti Surat 81411, 87024 Labuan, Wilayah Persekutuan Labuan, Malaysia',
                'latitude' => 5.3238,
                'longitude' => 115.2550,
                'radius_meters' => 150,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'name' => 'Institut Kemahiran Baitulmal (IKB)',
                'address' => 'Lot 2865, Jalan Bukit Persekutuan, Bukit Persekutuan, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1448,
                'longitude' => 101.6822,
                'radius_meters' => 100,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'name' => 'Pusat Rawatan Islam Wilayah Persekutuan (PUSRAWI)',
                'address' => 'No. 1, Jalan Tun Razak, 50400 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1577,
                'longitude' => 101.7142,
                'radius_meters' => 150,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'name' => 'Institut Profesional Baitulmal (IPB)',
                'address' => 'No. 23, Jalan Sri Semantan 1, Taman Sri Semantan, 50490 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1518,
                'longitude' => 101.6767,
                'radius_meters' => 100,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'name' => 'Kolej Sains Perubatan Antarabangsa PUSRAWI (PICOMS)',
                'address' => 'Lot 1030, Jalan Sungai Pusu, Gombak, 53100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2388,
                'longitude' => 101.7054,
                'radius_meters' => 200,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'name' => 'Pusat Wakaf MAIWP Sdn Bhd',
                'address' => 'Menara MAIWP, Tingkat 6, No. 39, Lrg Haji Hussein 2, Chow Kit, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1546,
                'longitude' => 101.6969,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'name' => 'Yayasan Taqwa',
                'address' => 'Tingkat 5, Menara MAIWP, No. 39, Lrg Haji Hussein 2, Chow Kit, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1546,
                'longitude' => 101.6969,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            // Tadika Permata MAIWP & MAIWP Kids
            [
                'id' => 21,
                'name' => 'Tadika Permata MAIWP Saidina Umar Al-Khattab',
                'address' => 'Jalan Bukit Damansara, Bukit Damansara, 50490 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1535,
                'longitude' => 101.6623,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'name' => 'Tadika Permata MAIWP Sumayyah',
                'address' => 'Jalan Sri Permaisuri 1, Bandar Sri Permaisuri, 56000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.0807,
                'longitude' => 101.7153,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'name' => 'Tadika Permata MAIWP TTDI',
                'address' => 'Jalan Datuk Sulaiman 7, Taman Tun Dr Ismail,60000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1488,
                'longitude' => 101.6365,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Tadika Permata MAIWP Intan Baiduri',
                'address' => 'Jalan Intan Baiduri 5A, Taman Intan Baiduri, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2157,
                'longitude' => 101.6548,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'name' => 'Tadika Permata MAIWP Al-Azim (Desa Tun Hussein Onn)',
                'address' => 'Jalan Jelatek 3, Desa Tun Hussein Onn, 54200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1673,
                'longitude' => 101.7308,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'name' => 'Tadika Permata MAIWP Al-Kauthar',
                'address' => 'No. 16, Jalan Raja Muda Musa, Kampung Baru, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1615,
                'longitude' => 101.7011,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Tadika Permata MAIWP An-Nur (Kg Cheras Baru)',
                'address' => 'Jalan Kuari, Kampung Cheras Baru, 56100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1148,
                'longitude' => 101.7529,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'name' => 'Tadika Permata MAIWP Datuk Keramat',
                'address' => 'Jalan Datuk Keramat, Kampung Datuk Keramat, 54000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1665,
                'longitude' => 101.7202,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'name' => 'Tadika Permata MAIWP At-Taufiqiah',
                'address' => 'Jalan Menteri, Off Jalan Gombak, 53000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1849,
                'longitude' => 101.6909,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Tadika Permata MAIWP Al-Watan (Kg Pandan)',
                'address' => 'Jalan Thaver, Kampung Pandan, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1431,
                'longitude' => 101.7283,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'name' => 'Tadika Permata MAIWP Tengku Ampuan Jemaah',
                'address' => 'Lorong Kg Periok Off Jalan Raja Alang, Kampung Baru, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1612,
                'longitude' => 101.6986,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'name' => 'Tadika Permata MAIWP Pulapol',
                'address' => 'Pusat Latihan Polis, Jalan Semarak, 50400 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1768,
                'longitude' => 101.7193,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'name' => 'Tadika Permata MAIWP Al-Farabi (Taman Sg Besi)',
                'address' => 'Jalan 1/108C, Taman Sungai Besi, 57100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.0947,
                'longitude' => 101.7125,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'name' => 'Tadika Permata MAIWP Aslahiyah (Flat Sri Selangor)',
                'address' => 'Flat Sri Selangor, Jalan San Peng, 55200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1404,
                'longitude' => 101.7059,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'name' => 'Tadika Permata MAIWP Al-Furqan (Presint 11, Putrajaya)',
                'address' => 'Jalan P11/1, Presint 11, 62300 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9118,
                'longitude' => 101.6687,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'name' => 'Tadika Permata MAIWP Ar-Rahman (Presint 16, Putrajaya)',
                'address' => 'Jalan P16/1, Presint 16, 62150 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9198,
                'longitude' => 101.6584,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'name' => 'Tadika Permata MAIWP Al-Hidayah (Presint 9, Putrajaya)',
                'address' => 'Jalan P9E/1, Presint 9, 62250 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9248,
                'longitude' => 101.6891,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'name' => 'Tadika Islam Maiwp Al Azim',
                'address' => 'Jalan Laksamana 1, Taman Maluri, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1354,
                'longitude' => 101.7342,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'name' => 'Tadika Islam Maiwp Taman Setapak Permai',
                'address' => 'Jalan 2/21D, Taman Setapak Permai, 53000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1978,
                'longitude' => 101.7105,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 40,
                'name' => 'Tadika Islam Maiwp Kasyiful Ulum',
                'address' => 'Jalan Radin Anum 1, Bandar Baru Sri Petaling, 57000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.0737,
                'longitude' => 101.7007,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 41,
                'name' => 'Tadika Islam MAIWP Ar-Rahman (Putrajaya)',
                'address' => 'Jalan P16/1, Presint 16, 62150 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9198,
                'longitude' => 101.6584,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 42,
                'name' => 'Tadika MAIWP Kids TTDI',
                'address' => 'No. 2A, Jalan Tun Mohd Fuad 3, Taman Tun Dr Ismail, 60000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1489,
                'longitude' => 101.6366,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 43,
                'name' => 'Tadika MAIWP Masjid Wilayah',
                'address' => 'Kompleks Masjid Wilayah Persekutuan, Jalan Tuanku Abdul Halim, Segambut, 52200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1685,
                'longitude' => 101.6753,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 44,
                'name' => 'Tadika Permata MAIWP Labuan',
                'address' => 'Jalan Merdeka, Bandar Labuan, 87000 Labuan, Wilayah Persekutuan Labuan, Malaysia',
                'latitude' => 5.2808,
                'longitude' => 115.2445,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 45,
                'name' => 'Tadika Permata MAIWP Presint 19',
                'address' => 'Jalan P19G, Presint 19, 62100 Putrajaya, Wilayah Persekutuan Putrajaya, Malaysia',
                'latitude' => 2.9203,
                'longitude' => 101.6943,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 46,
                'name' => 'Tadika Permata MAIWP Al-Azim (Jalan Jelatek)',
                'address' => 'No. 6, Jalan Jelatek 3, Desa Tun Hussein Onn, 54200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1673,
                'longitude' => 101.7308,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 47,
                'name' => 'Tadika Permata MAIWP An-Nur (Jalan Kuari)',
                'address' => 'Lot 2166, Jalan Kuari, Kampung Cheras Baru, 5610 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1148,
                'longitude' => 101.7529,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 48,
                'name' => 'Tadika Permata MAIWP At-Taufiqiah (Jalan Menteri)',
                'address' => 'No. 2, Jalan Menteri, Off Jalan Gombak, 53000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1849,
                'longitude' => 101.6909,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 49,
                'name' => 'Tadika Permata MAIWP Al-Watan (Jalan Thaver)',
                'address' => 'No. 35, Jalan Thaver, Kampung Pandan, 55100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1431,
                'longitude' => 101.7283,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 50,
                'name' => 'Tadika Permata MAIWP Tengku Ampuan Jemaah (Lorong Kg Periok)',
                'address' => 'No. 10, Lorong Kg Periok Off Jalan Raja Alang, Kampung Baru, 50300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1612,
                'longitude' => 101.6986,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 51,
                'name' => 'Tadika Permata MAIWP Al-Farabi (Jalan 1/108C)',
                'address' => 'No. 12, Jalan 1/108C, Taman Sungai Besi, 57100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.0947,
                'longitude' => 101.7125,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 52,
                'name' => 'Tadika Permata MAIWP Aslahiyah (Jalan San Peng)',
                'address' => 'Blok A, Tingkat Bawah, Flat Sri Selangor, Jalan San Peng, 55200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1404,
                'longitude' => 101.7059,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 53,
                'name' => 'Tadika Permata MAIWP Al-Hijrah (Kepong)',
                'address' => 'No. 1, Jalan 2/32, Taman Kepong Indah, 52100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2178,
                'longitude' => 101.6443,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 54,
                'name' => 'Tadika Permata MAIWP Nurul Yaqin',
                'address' => 'No. 23, Jalan Dato Haji Eusoff, Kompleks Darul Hidayah, 51000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1728,
                'longitude' => 101.6834,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 55,
                'name' => 'Tadika Permata MAIWP Al-Salam (Jalan Ipoh)',
                'address' => 'No. 346, Batu 4 1/2, Jalan Ipoh, 51200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1867,
                'longitude' => 101.6861,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 56,
                'name' => 'Tadika Permata MAIWP Al Husna (Sentul)',
                'address' => 'No. 33, Jalan Sentul Bahagia, Taman Sentul Bahagia, 51000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1763,
                'longitude' => 101.6881,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 57,
                'name' => 'Tadika Permata MAIWP Ad Dinniah (Jalan Ipoh)',
                'address' => 'No. 2A, Jalan Batu Ambar, Taman Kok Lian, Batu 5, Jalan Ipoh, 51200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1923,
                'longitude' => 101.6796,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 58,
                'name' => 'Tadika Permata MAIWP Al-Firdaus (Jalan Kuching)',
                'address' => 'No. 21, Jalan Kuching, Taman City, 51200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1745,
                'longitude' => 101.6865,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 59,
                'name' => 'Tadika Permata MAIWP Setapak Jaya',
                'address' => 'No. 12, Jalan Rejang 14, Taman Setapak Jaya, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1889,
                'longitude' => 101.7311,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 60,
                'name' => 'Tadika Permata MAIWP Daruttarbiah (Melewar)',
                'address' => 'No. 3, Jalan Melewar 1, Taman Melewar, 68100 Batu Caves, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2265,
                'longitude' => 101.6768,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 61,
                'name' => 'Tadika Permata MAIWP At-Taqwa (Taman Setapak)',
                'address' => 'No. 1A, Jalan 1/27A, Taman Setapak, 53200 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1953,
                'longitude' => 101.7047,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 62,
                'name' => 'Tadika Permata MAIWP Al-Ridhwaniah Seksyen 4 (Wangsa Maju)',
                'address' => 'No. 1, Jalan 4/27A, Seksyen 4, Wangsa Maju, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1928,
                'longitude' => 101.7412,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 63,
                'name' => 'Tadika Permata MAIWP Kem Genting Klang (Setapak)',
                'address' => 'Kem Genting Klang, Jalan Gombak, Setapak, 53000 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1995,
                'longitude' => 101.7041,
                'radius_meters' => 50,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 64,
                'name' => 'Tadika Permata MAIWP Al-Jamaiyyah (Setapak)',
                'address' => 'No. 676, Jalan F1, Taman Melati, Setapak, 53100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2078,
                'longitude' => 101.7315,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 65,
                'name' => 'Tadika Permata MAIWP Ibnu Sina (Gombak)',
                'address' => 'No. 1, Jalan SG 3/1, Taman Sri Gombak, 68100 Batu Caves, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2335,
                'longitude' => 101.6803,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 66,
                'name' => 'Tadika Permata MAIWP Taman Sri Rampai',
                'address' => 'No. 2, Jalan Sri Rampai 1, Taman Sri Rampai, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1992,
                'longitude' => 101.7448,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 67,
                'name' => 'Tadika Permata MAIWP Nur Al-Ihsan Seksyen 2 (Wangsa Maju)',
                'address' => 'No. 1, Jalan 2/27A, Seksyen 2, Wangsa Maju, 53300 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.1952,
                'longitude' => 101.7379,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
            [
                'id' => 68,
                'name' => 'Tadika Permata MAIWP Rumah Pangsa Gombak 1A (Taman Melati)',
                'address' => 'Blok 1A, Rumah Pangsa Gombak, Jalan Gombak, Taman Melati, 53100 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia',
                'latitude' => 3.2145,
                'longitude' => 101.7248,
                'radius_meters' => 30,
                'created_by' => 1,
                'updated_by' => null,
                'created_at' => now(),
                'updated_at' => null,
                'deleted_at' => null,
            ],
        ]);
    }
}
